### ISSUE TITLE
(UndefinedFunctionError) function Redix.Utils.sanitize_starting_opts/1 is undefined (module Redix.Utils is not available)

### ISSUE THREAD

**Issue by cottinisimone** [whatyouhide/redix_pubsub#21]
Hello,

We were trying to update redix version in order to update some other dependencies and we had troubles with redix_pubsub due to this error:

```
** (Mix) Could not start application fun_with_flags: FunWithFlags.Application.start(:normal, []) returned an error: shutdown: failed to start child: FunWithFlags.Notifications.Redis
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function Redix.Utils.sanitize_starting_opts/1 is undefined (module Redix.Utils is not available)
            Redix.Utils.sanitize_starting_opts([database: 1, port: 6379, host: "redis", name: :fun_with_flags_notifications, sync_connect: false])
            (redix_pubsub) lib/redix/pubsub.ex:290: Redix.PubSub.start_link/1
            (fun_with_flags) lib/fun_with_flags/notifications/redis.ex:71: FunWithFlags.Notifications.Redis.init/1
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

This problem seems to be that function Redix.Utils.sanitize_starting_opts/1 exists in Redix 0.8 version but not in 0.9.

This is our deps list

```
[
      {:httpoison, "~> 1.1"},
      {:phoenix, "~> 1.4"},
      {:plug_cowboy, "~> 1.0"},
      {:plug, "~> 1.7"},
      {:phoenix_pubsub, "~> 1.0"},
      {:phoenix_pubsub_redis, "~> 2.1"},
      {:phoenix_ecto, "~> 4.0"},
      {:ecto, "~> 3.0"},
      {:ecto_sql, "~> 3.0"},
      {:postgrex, ">= 0.0.0"},
      {:phoenix_html, "~> 2.6"},
      {:gettext, "~> 0.11"},
      {:redix, "~> 0.8"},
      {:credo, "~> 1.0", only: [:dev, :test]},
      {:excoveralls, "~> 0.7", only: :test},
      # gestisce i tipi enum in ecto/postgres
      {:ecto_enum, "~> 1.2"},
      {:logger_logstash_backend, github: "primait/logger_logstash_backend", ref: "master"},
      {:ex_prima_toolbox, ">= 0.0.0", only: :dev},
      {:distillery, "~> 2.0"},
      {:absinthe, "~> 1.3"},
      {:absinthe_relay, "~> 1.4"},
      {:absinthe_plug, "~> 1.3"},
      {:absinthe_ecto, "~> 0.1"},
      {:ex_aws, "~> 2.0"},
      {:ex_aws_s3, "~> 2.0"},
      {:sweet_xml, "~> 0.6"},
      {:briefly, "~> 0.3"},
      {:dialyxir, "1.0.0-rc.4", only: :dev, runtime: false},
      {:fetcher, "~> 0.1"},
      {:mime, "~> 1.1"},
      {:amqp, "~> 1.1"},
      {:timex, "~> 3.1"},
      {:exq, "~> 0.9"},
      {:exq_ui, "~> 0.9"},
      {:redix_pubsub, "~> 0.4"},
      {:http_mock_pal, ">= 0.0.0"},
      {:cors_plug, "~> 1.5"},
      {:bamboo, "~> 1.1"},
      {:bamboo_smtp, "~> 1.6"},
      {:quantum, "~> 2.3"},
      {:csv, "~> 2.1"},
      {:csv_schema, "~> 0.1"},
      {:mariaex, "~> 0.8"},
      {:hound, "~> 1.0", only: [:dev, :test]},
      {:ok, "~> 2.0"},
      {:posexional, "~> 0.4"},
      {:guardian, "~> 1.0"},
      {:cachex, "~> 3.0"},
      {:faker, "~> 0.11", only: [:dev, :test, :qa]},
      {:fun_with_flags, "~> 1.0"},
      {:fun_with_flags_ui, "~> 0.4"},
      {:basic_auth, "~> 2.2.2"},
      {:mock, "~> 0.3"},
      {:statix, github: "primait/statix", branch: "feature/switch_from_config"},
      {:jason, "~> 1.1"},
      {:jsx, "~> 2.8.0", override: true},
      {:phoenix_live_reload, "~> 1.2", only: :dev}
    ]
```

Thank you in advance

**Comment by whatyouhide** [comment]
If that works for you, you can upgrade to Redix 0.10.0, which now includes the pub/sub functionality (which means you don't have to depend on redix_pubsub anymore). Be sure to read through [the changelog](https://github.com/whatyouhide/redix/blob/master/CHANGELOG.md) in case you decide to update. If you still have problems, feel free to reopen this issue :)

**Comment by cottinisimone** [comment]
When you think 0.10 will be available?

**Comment by whatyouhide** [comment]
I'm sorry, I meant 0.9. Redix 0.9 already includes redix_pubsub.
